export const REALTIME_NAMESPACE = '/realtime'
export const REALTIME_DOMAIN_EVENT = 'DOMAIN_EVENT'

export const DomainEventTypes = {
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',
  TENANT_CREATED: 'TENANT_CREATED',
  TENANT_DEACTIVATED: 'TENANT_DEACTIVATED',
  TENANT_ACTIVATED: 'TENANT_ACTIVATED',
  TENANT_DELETED: 'TENANT_DELETED',
  TENANT_THEME_UPDATED: 'TENANT_THEME_UPDATED',
  AUDIT_CREATED: 'AUDIT_CREATED',
  DASHBOARD_UPDATED: 'DASHBOARD_UPDATED',
}
